name: Example - Basic

on:
  push:
    paths:
      - 'examples/basic/**'
      - '.github/workflows/example-basic.yml'
      - '.github/workflows/reusable-test.yml'
      - 'cth_*.cmake'
      - 'toolchain.cmake'
  pull_request:
    paths:
      - 'examples/basic/**'
      - '.github/workflows/example-basic.yml'
      - '.github/workflows/reusable-test.yml'
      - 'cth_*.cmake'
      - 'toolchain.cmake'

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      source_dir: examples/basic
      build_dir: examples/basic/build/preset-default
      exe_path_windows: examples/basic/build/preset-default/Release/basic_example_exec.exe
      exe_path_unix: examples/basic/build/preset-default/basic_example_exec
